services:
    database:
        restart: no
        ports:
            - ${DB__PORT?}:5432

    adminer:
        restart: no
        ports:
            - 8081:8080

        labels:
            - traefik.http.routers.${PROJECT?}-${ENV?}-adminer.rule=Host(`db.${DOMAIN?}`)
            - traefik.http.routers.${PROJECT?}-${ENV?}-adminer.entrypoints=web

    meilisearch:
        restart: no
        ports:
            - ${MS__PORT?}:7700

        labels:
            - traefik.http.routers.${PROJECT?}-${ENV?}-meilisearch.rule=Host(`search.${DOMAIN?}`)
            - traefik.http.routers.${PROJECT?}-${ENV?}-meilisearch.entrypoints=web

    mailcatcher:
        image: dockage/mailcatcher:0.9.0
        container_name: ${PROJECT?}-${ENV?}-mailcatcher
        restart: no
        ports:
            - 1080:1080 # web ui
            - ${EMAIL__SMTP_PORT?}:1025 # smtp

        labels:
            - traefik.enable=true
            - traefik.prod=${PROD?}
            - traefik.http.routers.${PROJECT?}-${ENV?}-mailcatcher.rule=Host(`mail.${DOMAIN?}`)
            - traefik.http.routers.${PROJECT?}-${ENV?}-mailcatcher.entrypoints=web
            - traefik.http.services.${PROJECT?}-${ENV?}-mailcatcher.loadbalancer.server.port=1080

    migrate-database:
        pull_policy: build
        build:
            context: ../../server
            target: dev

    reindex-meilisearch:
        pull_policy: build
        build:
            context: ../../server
            target: dev

    server:
        profiles:
            - include-client-server

        pull_policy: build
        build:
            context: ../../server
            target: dev

        restart: no
        ports:
            - 8000:8000

        volumes:
            - ../../server/data:/src/data
            - ../../server/logs:/src/logs

        develop:
            watch:
                - path: ../../server/app
                  action: sync
                  target: /src/app
                - path: ../../server/.dockerignore
                  action: rebuild
                - path: ../../server/Dockerfile
                  action: rebuild
                - path: ../../server/pyproject.toml
                  action: rebuild
                - path: ../../server/uv.lock
                  action: rebuild

        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'python -c "import urllib.request; urllib.request.urlopen(''http://server:8000/api/health'')"',
                ]

        labels:
            - traefik.http.routers.${PROJECT?}-${ENV?}-server.rule=Host(`api.${DOMAIN?}`)
            - traefik.http.routers.${PROJECT?}-${ENV?}-server.entrypoints=web

    client:
        profiles:
            - include-client-server

        pull_policy: build
        build:
            context: ../../client
            target: dev

        restart: no
        ports:
            - 5173:5173

        environment:
            - VITE_ENV=dev
            - VITE_IMAGE_TAG=local
            - VITE_API_URL=http://localhost:8000

        develop:
            watch:
                - path: ../../client/public
                  action: sync
                  target: /src/public
                - path: ../../client/src
                  action: sync
                  target: /src/src
                - path: ../../client/index.html
                  action: sync
                  target: /src/index.html
                - path: ../../client/Dockerfile
                  action: rebuild
                - path: ../../client/package-lock.json
                  action: rebuild
                - path: ../../client/package.json
                  action: rebuild
                - path: ../../client/tsconfig.app.json
                  action: rebuild
                - path: ../../client/tsconfig.json
                  action: rebuild
                - path: ../../client/tsconfig.node.json
                  action: rebuild
                - path: ../../client/vite.config.ts
                  action: rebuild

        labels:
            - traefik.http.routers.${PROJECT?}-${ENV?}-client.entrypoints=web
