name: ${PROJECT?}-${ENV?}

services:
    database:
        image: postgres:18
        container_name: ${PROJECT?}-${ENV?}-database
        restart: unless-stopped

        volumes:
            - pg-data:/var/lib/postgresql
        environment:
            - PGDATA=/var/lib/postgresql
            - POSTGRES_DB=${DB__NAME?}
            - POSTGRES_USER=${DB__USER?}
            - POSTGRES_PASSWORD=${DB__PASSWORD?}

        healthcheck:
            # pg_isready does not check user or db
            test: "psql -U ${DB__USER?} -d ${DB__NAME?} -c 'SELECT 1' || exit 1"
            start_period: 5s
            timeout: 5s
            retries: 3
            interval: 1m

    adminer:
        image: adminer:5
        container_name: ${PROJECT?}-${ENV?}-adminer
        restart: unless-stopped
        networks:
            - traefik-public
            - default

        environment:
            - ADMINER_DESIGN=dracula
            - ADMINER_DEFAULT_SERVER=database

        labels:
            - traefik.enable=true
            - traefik.prod=${PROD?}
            - traefik.http.routers.${PROJECT?}-${ENV?}-adminer.rule=Host(`db-${DOMAIN?}`)
            - traefik.http.routers.${PROJECT?}-${ENV?}-adminer.entrypoints=websecure

    meilisearch:
        image: getmeili/meilisearch:v1.40.0
        container_name: ${PROJECT?}-${ENV?}-meilisearch
        restart: unless-stopped
        networks:
            - traefik-public
            - default

        volumes:
            - meili-data:/meili_data
        environment:
            - MEILI_MASTER_KEY=${MS__MASTER_KEY?}

        healthcheck:
            test: 'curl -f http://localhost:7700/health || exit 1'
            start_period: 5s
            timeout: 5s
            retries: 3
            interval: 1m

        labels:
            - traefik.enable=true
            - traefik.prod=${PROD?}
            - traefik.http.routers.${PROJECT?}-${ENV?}-meilisearch.rule=Host(`search-${DOMAIN?}`)
            - traefik.http.routers.${PROJECT?}-${ENV?}-meilisearch.entrypoints=websecure

    migrations:
        image: ${DOCKER_REGISTRY?}/${PROJECT?}-${ENV?}-server:${TAG?}
        container_name: ${PROJECT?}-${ENV?}-migrations
        restart: no
        extra_hosts:
            - host.docker.internal:host-gateway

        depends_on:
            database:
                condition: service_healthy
                restart: true

        environment:
            - ENV=${ENV?}
            - LOG_LEVEL=${LOG_LEVEL?}
            - CLIENT_URL=${CLIENT_URL?}

            - ADMIN__USERNAME=${ADMIN__USERNAME?}
            - ADMIN__EMAIL=${ADMIN__EMAIL?}
            - ADMIN__FIRST_NAME=${ADMIN__FIRST_NAME?}
            - ADMIN__LAST_NAME=${ADMIN__LAST_NAME?}
            - ADMIN__PASSWORD=${ADMIN__PASSWORD?}

            - JWT__SECRET_KEY=${JWT__SECRET_KEY?}
            - JWT__ALGORITHM=${JWT__ALGORITHM?}
            - JWT__ACCESS_TOKEN_EXPIRE_MINUTES=${JWT__ACCESS_TOKEN_EXPIRE_MINUTES?}
            - JWT__REFRESH_TOKEN_EXPIRE_DAYS=${JWT__REFRESH_TOKEN_EXPIRE_DAYS?}

            # internal host & port
            - DB__HOST=database
            - DB__PORT=5432
            - DB__NAME=${DB__NAME?}
            - DB__USER=${DB__USER?}
            - DB__PASSWORD=${DB__PASSWORD?}

            # internal host & port
            - MS__HOST=meilisearch
            - MS__PORT=7700
            - MS__MASTER_KEY=${MS__MASTER_KEY?}

            - EMAIL__BACKEND=${EMAIL__BACKEND?}
            - EMAIL__EMAIL_FROM=${EMAIL__EMAIL_FROM?}
            # internal host
            - EMAIL__SMTP_HOST=host.docker.internal
            - EMAIL__SMTP_PORT=${EMAIL__SMTP_PORT?}
            # not required for non-smtp backends
            - EMAIL__SMTP_USERNAME=${EMAIL__SMTP_USERNAME}
            - EMAIL__SMTP_PASSWORD=${EMAIL__SMTP_PASSWORD}

            - GH__BACKEND=${GH__BACKEND?}
            # not required for console backend
            - GH__REPO_OWNER=${GH__REPO_OWNER}
            - GH__TOKEN=${GH__TOKEN}
            - GH__ISSUE_ASSIGNEE=${GH__ISSUE_ASSIGNEE}

        command: alembic upgrade head

    server:
        image: ${DOCKER_REGISTRY?}/${PROJECT?}-${ENV?}-server:${TAG?}
        container_name: ${PROJECT?}-${ENV?}-server
        restart: unless-stopped
        networks:
            - traefik-public
            - default
        extra_hosts:
            - host.docker.internal:host-gateway

        depends_on:
            database:
                condition: service_healthy
                restart: true
            migrations:
                condition: service_completed_successfully

        volumes:
            - server-data:/src/data
            - server-logs:/src/logs
        environment:
            - ENV=${ENV?}
            - LOG_LEVEL=${LOG_LEVEL?}
            - CLIENT_URL=${CLIENT_URL?}

            - ADMIN__USERNAME=${ADMIN__USERNAME?}
            - ADMIN__EMAIL=${ADMIN__EMAIL?}
            - ADMIN__FIRST_NAME=${ADMIN__FIRST_NAME?}
            - ADMIN__LAST_NAME=${ADMIN__LAST_NAME?}
            - ADMIN__PASSWORD=${ADMIN__PASSWORD?}

            - JWT__SECRET_KEY=${JWT__SECRET_KEY?}
            - JWT__ALGORITHM=${JWT__ALGORITHM?}
            - JWT__ACCESS_TOKEN_EXPIRE_MINUTES=${JWT__ACCESS_TOKEN_EXPIRE_MINUTES?}
            - JWT__REFRESH_TOKEN_EXPIRE_DAYS=${JWT__REFRESH_TOKEN_EXPIRE_DAYS?}

            # internal host & port
            - DB__HOST=database
            - DB__PORT=5432
            - DB__NAME=${DB__NAME?}
            - DB__USER=${DB__USER?}
            - DB__PASSWORD=${DB__PASSWORD?}

            # internal host & port
            - MS__HOST=meilisearch
            - MS__PORT=7700
            - MS__MASTER_KEY=${MS__MASTER_KEY?}

            - EMAIL__BACKEND=${EMAIL__BACKEND?}
            - EMAIL__EMAIL_FROM=${EMAIL__EMAIL_FROM?}
            # internal host
            - EMAIL__SMTP_HOST=host.docker.internal
            - EMAIL__SMTP_PORT=${EMAIL__SMTP_PORT?}
            # not required for non-smtp backends
            - EMAIL__SMTP_USERNAME=${EMAIL__SMTP_USERNAME}
            - EMAIL__SMTP_PASSWORD=${EMAIL__SMTP_PASSWORD}

            - GH__BACKEND=${GH__BACKEND?}
            # not required for console backend
            - GH__REPO_OWNER=${GH__REPO_OWNER}
            - GH__TOKEN=${GH__TOKEN}
            - GH__ISSUE_ASSIGNEE=${GH__ISSUE_ASSIGNEE}

        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'python -c "import urllib.request; urllib.request.urlopen(''http://localhost:8000/api/health'')"',
                ]
            start_period: 5s
            timeout: 5s
            retries: 3
            interval: 1m

        labels:
            - traefik.enable=true
            - traefik.prod=${PROD?}
            - traefik.http.routers.${PROJECT?}-${ENV?}-server.rule=Host(`api-${DOMAIN?}`)
            - traefik.http.routers.${PROJECT?}-${ENV?}-server.entrypoints=websecure

    client:
        image: ${DOCKER_REGISTRY?}/${PROJECT?}-${ENV?}-client:${TAG?}
        container_name: ${PROJECT?}-${ENV?}-client
        restart: unless-stopped
        networks:
            - traefik-public
            - default

        depends_on:
            server:
                condition: service_healthy

        labels:
            - traefik.enable=true
            - traefik.prod=${PROD?}
            - traefik.http.routers.${PROJECT?}-${ENV?}-client.rule=Host(`${DOMAIN?}`)
            - traefik.http.routers.${PROJECT?}-${ENV?}-client.entrypoints=websecure

volumes:
    pg-data:
    meili-data:
    server-data:
    server-logs:

networks:
    traefik-public:
        external: true
        name: ${TRAEFIK_NETWORK:-traefik-public}
