#!/bin/sh
set -Eeuo pipefail

echo "Running pre-commit hook..."
echo

echo "Forcing API client generation..."
./scripts/generate_api.sh -f

if ! git diff --quiet -- "client/src/api/generated"; then
    echo "API client code is outdated"
    echo "Stage updated files"
    exit 1
fi

echo "API client code is up to date"
echo

echo "Scanning GitHub Actions files..."
zizmor .github/
echo

echo "Formatting and linting staged files..."
lint-staged
echo

echo "Checking for available updates..."
echo "Checking base project..."
ncu
echo

echo "Checking client project..."
ncu --cwd client
echo
