name: CI / Check Lint and Format

on:
    workflow_dispatch:
    pull_request:
        branches:
            - stage
            - main

permissions: {}

jobs:
    check-lint-and-format:
        name: Check Lint and Format
        if: github.event_name != 'pull_request' || github.actor != 'dependabot[bot]'
        uses: ./.github/workflows/lint-and-format.yml
        with:
            mode: check
        permissions:
            contents: write
