name: CI / Dependency Review

on:
    workflow_dispatch:
    pull_request_target:
        branches:
            - stage
            - main

permissions:
    contents: none

jobs:
    dependency-review:
        name: Dependency Review
        runs-on: self-hosted
        environment: ${{ github.base_ref == 'main' && 'prod' || github.base_ref }}
        steps:
            - name: checkout
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.pull_request.head.sha || github.ref_name }}

            - name: run
              uses: actions/dependency-review-action@v4
              with:
                  base-ref: ${{ github.event.pull_request.base.sha || github.event.repository.default_branch }}
                  head-ref: ${{ github.event.pull_request.head.sha || github.sha }}
