name: CD / Deploy Client Image (Reusable)

on:
    workflow_call:
        inputs:
            runner:
                required: true
                type: string
            tag:
                required: true
                type: string

permissions:
    contents: none

jobs:
    deploy-client:
        name: Deploy Client Image
        runs-on: ${{ inputs.runner }}
        environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: log in to docker registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ secrets.DOCKER_REGISTRY }}
                  username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
                  logout: false

            - name: set up docker buildx
              uses: docker/setup-buildx-action@v3

            - name: build & push docker image
              uses: docker/build-push-action@v6
              with:
                  context: client
                  push: true
                  tags: ${{ secrets.DOCKER_REGISTRY }}/${{ vars.PROJECT }}-${{ vars.ENV }}-client:${{ inputs.tag }}
                  build-args: |
                      VITE_ENV=${{ vars.ENV }}
                      VITE_IMAGE_TAG=${{ inputs.tag }}
                      VITE_API_URL=${{ secrets.VITE_API_URL }}
                  cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/cache/${{ vars.PROJECT }}-${{ vars.ENV }}-client:buildkit
                  cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/cache/${{ vars.PROJECT }}-${{ vars.ENV }}-client:buildkit,mode=max
