name: CD / Deploy Application

on:
    workflow_dispatch:
    push:
        branches:
            - stage
            - main
        paths:
            - .github/workflows/deploy*.yml
            - client/public/**
            - client/src/**
            - client/Dockerfile
            - client/index.html
            - client/nginx.conf
            - client/package.json
            - client/pnpm-lock.yaml
            - client/pnpm-workspace.yaml
            - client/tsconfig*.json
            - client/vite.config.ts
            - config/**
            - server/app/**
            - server/alembic.ini
            - server/Dockerfile
            - server/pyproject.toml
            - server/uv.lock

concurrency:
    group: deploy-${{ github.ref_name }}
    cancel-in-progress: true

permissions: {}

jobs:
    set-variables:
        name: Set Variables
        runs-on: self-hosted
        environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
        outputs:
            runner: ${{ steps.set_runner.outputs.runner }}
            tag: ${{ steps.set_tag.outputs.tag }}
        steps:
            - name: set runner
              id: set_runner
              run: echo "runner=mbp-13-ubuntu" >> $GITHUB_OUTPUT

            - name: set tag
              id: set_tag
              run: |
                  VERSION=${{ github.run_number }}-${{ github.run_attempt }}-${{ github.run_id }}
                  echo "tag=$(date +%Y-%m-%d).$VERSION" >> $GITHUB_OUTPUT

    deploy-client:
        name: Deploy Client Image (Reusable)
        needs: set-variables
        uses: ./.github/workflows/deploy-client.yml
        with:
            runner: ${{ needs.set-variables.outputs.runner }}
            tag: ${{ needs.set-variables.outputs.tag }}
        secrets:
            DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
            DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
            DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    deploy-server:
        name: Deploy Server Image (Reusable)
        needs: set-variables
        uses: ./.github/workflows/deploy-server.yml
        with:
            runner: ${{ needs.set-variables.outputs.runner }}
            tag: ${{ needs.set-variables.outputs.tag }}
        secrets:
            DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
            DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
            DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    deploy-infra:
        name: Deploy Infrastructure (Reusable)
        needs: [set-variables, deploy-client, deploy-server]
        uses: ./.github/workflows/deploy-infra.yml
        with:
            runner: ${{ needs.set-variables.outputs.runner }}
            tag: ${{ needs.set-variables.outputs.tag }}
        secrets: inherit # zizmor: ignore[secrets-inherit] - all secrets required
