name: Maintenance / Format and Lint after PR Merge

on:
    workflow_run:
        workflows: ['Maintenance / Generate API Client after PR Merge']
        types:
            - completed

permissions:
    contents: write

jobs:
    format-and-lint:
        name: Format and Lint
        runs-on: self-hosted
        steps:
            - name: set cache dirs
              run: |
                  echo "PNPM_STORE_DIR=$HOME/.cache/pnpm/store" >> $GITHUB_ENV
                  echo "UV_CACHE_DIR=$HOME/.cache/uv" >> $GITHUB_ENV

            - name: checkout
              uses: actions/checkout@v6
              with:
                  ref: stage

            - name: setup pnpm
              uses: pnpm/action-setup@v5
              with:
                  version: latest

            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 'lts/*'
                  check-latest: true

            - name: set pnpm config
              run: |
                  mkdir -p "$PNPM_STORE_DIR"
                  pnpm config set store-dir "$PNPM_STORE_DIR"
                  pnpm config list

            - name: cache pnpm store
              uses: actions/cache@v4
              with:
                  path: ${{ env.PNPM_STORE_DIR }}
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml', 'client/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: install deps - base
              run: pnpm i --frozen-lockfile --ignore-scripts

            - name: install deps - client
              working-directory: client
              run: pnpm i --frozen-lockfile

            - name: setup uv
              uses: astral-sh/setup-uv@v7
              with:
                  working-directory: server
                  enable-cache: true
                  cache-dependency-glob: uv.lock

            - name: install deps - server
              working-directory: server
              run: uv sync

            - name: format & lint
              run: |
                  pnpm run format
                  pnpm run lint

            - name: commit & push
              run: |
                  if [[ -n "$(git status --porcelain)" ]]; then
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"

                    git add .
                    git status
                    git commit -m "chore: format & lint after PR merge"
                    git status
                    git push
                  else
                    echo "No formatting changes to commit"
                  fi
