name: CI / Test Server

on:
    workflow_dispatch:
    pull_request_target:
        branches:
            - stage
            - main

permissions:
    contents: none

jobs:
    test-server:
        name: Test Server
        runs-on: self-hosted
        environment: test
        steps:
            - name: set cache dir
              run: |
                  echo "UV_CACHE_DIR=$HOME/.cache/uv" >> $GITHUB_ENV

            - name: checkout
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.pull_request.head.sha || github.ref_name }}

            - name: setup uv
              uses: astral-sh/setup-uv@v7
              with:
                  working-directory: server
                  enable-cache: true
                  cache-dependency-glob: uv.lock

            - name: install deps
              working-directory: server
              run: uv sync

            - name: run deptry
              working-directory: server
              run: make deptry

            - name: run type checks
              working-directory: server
              run: make check

            - name: run tests with coverage
              working-directory: server
              run: make cov
